version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
        
  setup_cqc:
    run: r:latest analysis/setup_cqc_data.R data/pc_to_msoa.csv data/carehomes_cqc.csv
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: cqc_setup_log.txt
        data1: cqc_all.csv
        data2: cqc_by_msoa.csv

  run_report:
    run: r:latest analysis/report.R output/input.csv cqc_by_msoa.csv
    needs: [generate_study_population, setup_cqc]
    outputs:
      moderately_sensitive:
        log: report_output.txt

