version: '3.0'

expectations:
  population_size: 1000

actions:

  00_generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  01_cross_tabulations:
    run: r:latest analysis/01_cross_tabulations.R 
    needs: [00_generate_cohort]
    outputs:
      moderately_sensitive:
        log: analysis/outfiles/01_cross_tabulations.txt

  02_characteristics:
    run: r:latest analysis/02_characteristics.R 
    needs: [01_cross_tabulations]
    outputs:
      moderately_sensitive:
        log: analysis/outfiles/02_characteristics.txt


