version: '3.0'

expectations:
  population_size: 1000

actions:

  00_generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  01_cross_tabulations:
    run: r:latest analysis/01_cross_tabulations.R ./output/input_2019.csv
    outputs:
      moderately_sensitive:
        log: analysis/01_cross_tabulations.txt


